const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0FiNmEwZERiSW00dDJYRVpxNm5Ca2k2KzUvNE9qd0NwMFhGaE95ZmdYYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaDZxU3JpY1llem0yQUI0ZzBDYWMzTm5SQUx6QzRuTFFhWStqTUp4R2xBYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4S0RZb3JtdlNaOFBnbTFzV3RBTXlGRFRZYXN2enE4SWJsVnFVWDRJQ1hjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZNU9Sa3lmV2ZnUmxuMHFiZ2RoK3dLWG9iZFdsbTZ0amhwMjdHVmRiU2dnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9IZUxWK0wvaE9wTjBWRjE0M1pLMXlISy9jQitRNHFCblRaWU10N2hwWGc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InJHMG1yK2lWa3hCTDNsS0orSjdrU0x2bEF5dktFTFZaTm9CdCtCcDVra2s9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ01TRVlIRVZ5MDlXUGFQQzZiRDlrS1Y1TW5RQjNzTWhRYnpnbitRWU8yOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0ZIeEh2Y2ZuZjNKbHhZVG1JbDdpVVUya041TGx5b1lWdWNlRlFTb2dWST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlkybGwvTE5mS2dnWXkwSkdNeXB5bWhpUXlGVkpvazFCdk13ZnF4WC90Nkh4L1Z1Slo3RkkwQWtncWFsWDNyQjI2QU5DY3lULyswbk02Ujg3ZENoNmdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAzLCJhZHZTZWNyZXRLZXkiOiJ3RFJ4OXFuMVZDYUlTYVRpa20zR21jOFF5eE5JTVNJTDVpS20zQXVqa21VPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOnRydWV9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6Ijk5MTRVTDZBIiwibWUiOnsiaWQiOiIyNTQxMTI1ODE4MTA6MTFAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxODgwNzcyNzIyNDg1MjM6MTFAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOMlI0Y0lERU9UMWw4MEdHQVFnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJCLzZWZXcxenNUOTVBV3Z4OW5WcDlVZ3dNN0huOFhXb2hjazhZMFlGNmkwPSIsImFjY291bnRTaWduYXR1cmUiOiJiaU16aWNETGRDYmpKSGZNQUl1eHlWeGFTdktXOEJ0TzMyR0pWbGt5WGFyTjExd25YdVZ6ellHVXdPQ2ZyUnBYa29Ka0pKYmxVYTFFWFdyMEhTUkVBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoic3Z0QkovUTVVZHdEd1A5d3hxSWlpSXJBUWJxWEhYMXhqVXVicTYwTFpGV2t3UFNpclU0Q0JBUDVsTEorTm1pdEZCTnRSTmJWS2hiZjVJU20zc1U1alE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQxMTI1ODE4MTA6MTFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUWYrbFhzTmM3RS9lUUZyOGZaMWFmVklNRE94NS9GMXFJWEpQR05HQmVvdCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSURRZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzcyNDg1MzYwLCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTWdPIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
